tasks:
    - dataset: crispr_genomic
      model: deepbind
      loss: mse
      batch_size: 512
      num_filters: 256
      hidden_dim: 256
      output_size: 1

training:
    optimizer: adam
    lr: 0.001

projectors:
    context_size: 0

optimization:
    steps_per_generation: 1000
    num_generations: 1000
    final_training_generations: 0
