tasks:
    - dataset: synthetic
      task_index: 0
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 1
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 2
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 3
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 4
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 5
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 6
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 7
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 8
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 9
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 10
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 11
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 12
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 13
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 14
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 15
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 16
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 17
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 18
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 19
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 20
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 21
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 22
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 23
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 24
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 25
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 26
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 27
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 28
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1
    - dataset: synthetic
      task_index: 29
      noisy: True
      model: linear_model
      loss: mse
      num_val: 5
      batch_size: 10
      input_size: 20
      output_size: 1

training:
    optimizer: adam
    lr: 0.001

projectors:
    context_size: 1
    block_in: 20
    block_out: 1
    bias: False

optimization:
    steps_per_generation: 100
    num_generations: 1000
    generate_percentage: 0.5
    alternatives_per_generation: 4
    selection_method: best
    soft_lr: 0.01
    reactivation_probability: 0.0001
    final_training_generations: 200
    save_best: True
